[package]
name = "tyconv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
toml = "0.5"
serde_yaml = "0.8"
xjbutil = { version = "0.5", features = ["std-ext"] }